title: CompuClara
tagline: Informática clara y sin complicaciones
avatar: /assets/img/avatar.png
description: >-
  Hardware, redes y sistemas. ¿Dudas con tu PC?
  Soluciones y recomendaciones de verdad.

url: "https://compuclaratech.github.io"
baseurl: ""

lang: es
timezone: Europe/Madrid

github:
  username: compuclaratech

social:
  name: CompuClara
  email: compuclara.tech@gmail.com
  links:
    - https://www.instagram.com/compuclara.tech
    - https://www.tiktok.com/@compuclara.tech
    - https://compuclara.blogspot.com

theme: jekyll-theme-chirpy

plugins:
  - jekyll-feed

# Build settings
future: false
show_excerpts: true