title: CompuClara
email: compuclara.tech@gmail.com
description: >-
  Informática clara y sin complicaciones. Hardware, redes y sistemas.
  ¿Dudas con tu PC? Soluciones y recomendaciones de verdad.
baseurl: ""
url: "https://compuclaratech.github.io"
twitter_username: compuclara
github_username: compuclaratech

# Build settings
theme: minima
plugins:
  - jekyll-feed